-- Add PEP workflow columns to kyc_clients_decrypted view
-- These columns exist on the base kyc_clients table but were not exposed in the decrypted view.
-- All are plain (non-encrypted) columns, so no decryption logic is needed.

DROP VIEW IF EXISTS kyc_clients_decrypted;

CREATE VIEW kyc_clients_decrypted AS
SELECT
  id,
  organization_id,
  matter_id,
  created_by,
  created_at,
  updated_at,
  deleted_at,
  deletion_reason,
  client_type,
  client_status,
  onboarding_status,
  customer_type,
  customer_status,
  date_of_birth,
  nationality,
  country_of_residence,
  email,
  business_activity,
  industry_sector,
  registration_number,
  registration_country,
  source_of_funds,
  source_of_wealth,
  estimated_annual_income,
  estimated_net_worth,
  purpose_of_relationship,
  expected_transaction_volume,
  expected_transaction_frequency,
  pep_status,
  pep_details,
  pep_declaration,
  pep_category,
  pep_confirmed_at,
  pep_confirmed_by,
  pep_senior_approver_name,
  pep_senior_approved_at,
  pep_senior_approval_notes,
  pep_sow_sof_reference,
  pep_family_associates,
  pep_enhanced_monitoring,
  sanctioned_entity,
  adverse_media,
  base_risk_score,
  current_risk_rating,
  current_dd_level,
  total_risk_score,
  risk_level,
  risk_assessment,
  enhanced_dd_required,
  edd_required,
  edd_reason,
  aml_trigger_activities,
  alert_count,
  monitoring_frequency,
  monitoring_status,
  review_frequency,
  next_review_date,
  last_review_date,
  senior_approval_status,
  senior_approval_date,
  senior_approval_by,
  senior_approval_notes,
  ownership_structure_verified,
  source_of_funds_verified,
  sof_verification_date,
  sof_verified_by,
  source_of_wealth_verified,
  sow_verified_by,
  sow_verification_date,
  first_payment_verified,
  relationship_manager_id,
  compliance_officer_assigned,
  customer_data,
  policy_information,
  sanctions_screening,
  ongoing_monitoring,
  suspicious_indicators,
  customer_declaration,
  compliance_approval,
  decrypt_pii(client_name_encrypted) AS client_name,
  decrypt_pii(national_id_encrypted) AS national_id,
  decrypt_pii(passport_number_encrypted) AS passport_number,
  decrypt_pii(phone_encrypted) AS phone,
  decrypt_pii(address_encrypted) AS address,
  decrypt_pii(tax_id_encrypted) AS tax_id,
  CASE
    WHEN beneficiaries_encrypted IS NOT NULL THEN decrypt_pii(beneficiaries_encrypted)::jsonb
    ELSE beneficiaries
  END AS beneficiaries,
  CASE
    WHEN beneficial_owners_encrypted IS NOT NULL THEN decrypt_pii(beneficial_owners_encrypted)::jsonb
    ELSE beneficial_owners
  END AS beneficial_owners,
  decrypt_pii(payer_name_encrypted) AS payer_name,
  decrypt_pii(payer_identification_encrypted) AS payer_identification,
  retention_until
FROM kyc_clients
WHERE deleted_at IS NULL;

-- Recreate RLS policies on the view (views inherit RLS from the underlying table,
-- but we need to ensure the view is accessible to authenticated users)
GRANT SELECT ON kyc_clients_decrypted TO authenticated;
